### ISSUE TITLE
Allow users to provide their own dependency to imports mapping

### ISSUE THREAD

**Issue by Nour-Mws** [tweag/FawltyDeps#260]
Check #256 to see how this fits into the overall mapping strategy.

**Comment by jherland** [comment]
Remember to have a look at other tools that provide a way for users to define their own package -> import mapping, e.g. Pants.

**Comment by mknorps** [comment]
[Creosote](https://github.com/fredrikaverpil/creosote) does not have an option for user-defined mapping.

**Comment by mknorps** [comment]
We may use TOML format for `mappings.toml`. It gives a user option to comment is readable and easily editable:
```toml
  apache-airflow = ["airflow"]
  atlassian-python-api = ["atlassian"]
  attrs = ["attr", "attrs"]
```

**Comment by jherland** [comment]
I agree that TOML is a good format for this mapping, but I wonder if it has to be a different file than `pyproject.toml`? By keeping it in `pyproject.toml`, we:
- don't have to parse any more files than we already do
- don't have to document this new file to the user, instead their mapping can be defined right next to their other FD configuration in a new `[tool.fawltydeps.custom_mapping]` section.
- can rely on the existing deserialization provided by pydantic to support passing the same mapping via the environment for free, that is, the `pyproject.toml` section:
```toml
[tool.fawltydeps.custom_mapping]
apache-airflow = ["airflow"]
atlassian-python-api = ["atlassian"]
attrs = ["attr", "attrs"]
```
can also be expressed as a similar JSON-formatted environment variable:
```sh
fawltydeps_custom_mapping='{ \
  "apache-airflow": ["airflow"], \
  "atlassian-python-api": ["atlassian"], \
  "attrs": ["attr", "attrs"] \
}'
```
and both can end up in our `Settings` object as a `dict`:
```python
settings.custom_mapping: Dict[str, Set[str]] = {
    "apache-airflow": {"airflow"},
    "atlassian-python-api": {"atlassian"},
    "attrs": {"attr", "attrs"},
}
```

This can also be achieved with the mapping stored in a separate file, but I don't yet see the advantages of keeping it separate?
