### ISSUE TITLE
Explore changes needed to support Windows and MacOS

### ISSUE THREAD

**Issue by Nour-Mws** [tweag/FawltyDeps#355]
Prompted by a slack discussion related to https://github.com/tweag/FawltyDeps/issues/226#issuecomment-1689667809.
This includes adding those to the CI matrix.

**Comment by mknorps** [comment]
Expanding matrix to:
```yaml
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        os: [macos-latest, windows-latest, ubuntu-latest]
```
CI components results are:
- listing **OK**
- formatting **OK**
- self_test  **OK**
- tests **FAIL**

Tests fail for all combinations of `windows-latest` and Python versions on command line tests (see https://github.com/tweag/FawltyDeps/actions/runs/6626043803/job/17998184203).

Tests on MacOS are all passing.
