### ISSUE TITLE
Fail on invalid `pyproject.toml` dependencies sections?

### ISSUE THREAD

**Issue by Nour-Mws** [tweag/FawltyDeps#358]
This a follow-up to PR #351.
We currently support `pyproject.toml` files having both dynamic and static dependencies, including some states that are not valid. This is the case in the following example where `optional-dependencies` is flagged as dynamic then defined both in `[tool.setuptools.dynamic]` and in `[project]`. Attempting to pass this through `setuptools` will result in an error as soon as the line with the static definition of `optional-dependencies` is parsed.

We're not a `pyproject.toml` linter, but I feel uneasy making analysis on the basis of an invalid `pyproject.toml`.

I'm wondering if there's an easy way to source out this validation the [way we've done](https://github.com/tweag/FawltyDeps/pull/227) with `pip-requirements-parser`?
 
```toml
[project]
name = "MyLib"
dynamic = ["optional-dependencies"]
dependencies = ["django"]
optional-dependencies = {"dev" = ["black"]}
[tool.setuptools.dynamic]
dependencies = { file = [".subdir/requirements.txt"] }
optional-dependencies.test = { file = [".subdir/requirements-test.txt"]
```
