### ISSUE TITLE
Add support for the UniDep package management tool?

### ISSUE THREAD

**Issue by jherland** [tweag/FawltyDeps#458]
Another package management tool in the Conda + Pip space that I've come across is UniDep ("Unified Conda and Pip Dependency Management"): https://github.com/basnijholt/unidep. I am unsure how much it is used, and if there is any demand for supporting it with FawltyDeps. Supporting it with FawltyDeps should be relatively straightforward:
- It is configured either via:
  - a `[tool.unidep]` section in `pyproject.toml` that contains a dependencies table like this:
    ```toml
    [tool.unidep]
    dependencies = [
        "some-package >=1:unix",
        "another-package:win",
        "special-package:osx64",
        { pip = "cirq:macos win", conda = "cirq:linux" },
    ]
    ```
  - or a `requirements.yaml` file with a similar dependencies table:
    ```yaml
    dependencies:
      - some-package >=1  # [unix]
      - another-package   # [win]
      - special-package   # [osx64]
      - pip: cirq         # [macos win]
        conda: cirq       # [linux]
    ```
- I'm not 100% sure what a UniDep environment looks like, but their [FAQ](https://github.com/basnijholt/unidep?tab=readme-ov-file#-faq) describes it as a wrapper for pip + conda: "UniDep uses pip and conda under the hood to install dependencies". Therefore I suspect that existing support for such environments in FawltyDeps should be sufficient.
